### ISSUE TITLE
port mac2012.sh to ansible

### ISSUE THREAD

**Issue by pbustosl** [agustux/mac2012#2]
```
# create a python virtual env to avoid messing with your system's python:
python3 -m venv ansible_venv
# upgrade its pip:
./ansible_venv/bin/python3 -m pip install --upgrade pip
# install the minimal ansible (just core modules)
./ansible_venv/bin/python3 -m pip install ansible-core
```

create `ansible/ansible.cfg `:
```
[defaults]
localhost_warning = false

[inventory]
inventory_unparsed_warning = false
```
create `ansible/mac2012.yml`:
```
- hosts: localhost
  connection: local
  tasks:
  - name: check if this is a VM
    shell: "lsusb | grep -q QEMU"
    register: found_quemu
```

how to run your playbook:
```
ANSIBLE_CONFIG=ansible/ansible.cfg ./ansible_venv/bin/ansible-playbook \
  ansible/mac2012.yml
```
